In [2]:
import pandas as pd

In [11]:
df = pd.read_csv("./IPL_Matches_2008_2022.csv")
df = df.drop(columns=["City", "Venue", "method", "Player_of_Match", "Umpire1", "Umpire2", "Team1Players", "Team2Players"])
# TODO:  What are these No result matches and why are they there?
# df.dropna(inplace=True)

df.head()

,ID,Date,Season,MatchNumber,Team1,Team2,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin
0,1312200,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0
1,1312199,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0
2,1312198,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0
3,1312197,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0
4,1304116,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0

In [12]:
df[df["SuperOver"] != "N"]

,ID,Date,Season,MatchNumber,Team1,Team2,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin
114,1254077,2021-04-25,2021,20,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Y,Delhi Capitals,SuperOver,NaN
158,1216512,2020-10-18,2020/21,35,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Y,Kolkata Knight Riders,SuperOver,NaN
159,1216517,2020-10-18,2020/21,36,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Y,Kings XI Punjab,SuperOver,NaN
184,1216547,2020-09-28,2020/21,10,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Y,Royal Challengers Bangalore,SuperOver,NaN
192,1216493,2020-09-20,2020/21,2,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Y,Delhi Capitals,SuperOver,NaN
203,1178426,2019-05-02,2019,51,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Y,Mumbai Indians,SuperOver,NaN
205,1178424,2019-04-30,2019,49,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NoResults,NaN
244,1175365,2019-03-30,2019,10,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,Y,Delhi Capitals,SuperOver,NaN
339,1082625,2017-04-29,2017,35,Gujarat Lions,Mumbai Indians,Gujarat Lions,bat,Y,Mumbai Indians,SuperOver,NaN
437,829813,2015-05-17,2015,55,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,NaN,NoResults,NaN
464,829763,2015-04-29,2015,29,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NoResults,NaN
474,829741,2015-04-21,2015,18,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Y,Kings XI Punjab,SuperOver,NaN
533,729315,2014-04-29,2014,19,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,bat,Y,Rajasthan Royals,SuperOver,NaN
608,598017,2013-04-16,2013,21,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,Y,Royal Challengers Bangalore,SuperOver,NaN
621,598004,2013-04-07,2013,7,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Y,Sunrisers Hyderabad,SuperOver,NaN
708,501265,2011-05-21,2011,68,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,NaN,NoResults,NaN
819,419121,2010-03-21,2009/10,16,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,field,Y,Kings XI Punjab,SuperOver,NaN
883,392190,2009-04-23,2009,10,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Y,Rajasthan Royals,SuperOver,NaN